<?php
	$tbf_info = array();
	$tab_info = array();
	$role_info = array();
	include('previleges/table/previleges_ums_table_afile.php');
	include('previleges/table/previleges_ums_table_arole.php');
	include('previleges/table/previleges_ums_table_arole_bf.php');
	include('previleges/table/previleges_ums_table_arole_type.php');
	include('previleges/table/previleges_ums_table_auser.php');
	include('previleges/table/previleges_ums_table_bfunction.php');
	include('previleges/table/previleges_ums_table_bfunction_type.php');
	include('previleges/table/previleges_ums_table_city.php');
	include('previleges/table/previleges_ums_table_country.php');
	include('previleges/table/previleges_ums_table_doc_type.php');
	include('previleges/table/previleges_ums_table_jobrole.php');
	include('previleges/table/previleges_ums_table_job_arole.php');
	include('previleges/table/previleges_ums_table_module.php');
	include('previleges/table/previleges_ums_table_module_auser.php');
	include('previleges/table/previleges_ums_table_module_orgunit.php');
	include('previleges/table/previleges_ums_table_module_status.php');
	include('previleges/table/previleges_ums_table_module_type.php');
	include('previleges/table/previleges_ums_table_region.php');
	include('previleges/table/previleges_ums_table_ugroup.php');
	include('previleges/table/previleges_ums_table_ugroup_scope.php');
	include('previleges/table/previleges_ums_table_ugroup_type.php');
	include('previleges/role/previleges_ums_role35.php');
	include('previleges/role/previleges_ums_role203.php');
	include('previleges/role/previleges_ums_role345.php');
	include('previleges/role/previleges_ums_role416.php');
	include('previleges/role/previleges_ums_role390.php');
	include('previleges/role/previleges_ums_role204.php');
	include('previleges/role/previleges_ums_role414.php');
	include('previleges/role/previleges_ums_role389.php');
	include('previleges/role/previleges_ums_role415.php');
	include('previleges/role/previleges_ums_role199.php');
	include('previleges/role/previleges_ums_role200.php');
	include('previleges/role/previleges_ums_role201.php');
	include('previleges/role/previleges_ums_role202.php');

 ?>